# Generated by Django 5.2.1 on 2025-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(related_name='resources', to='core.tag'),
        ),
    ]
