# Generated by Django 5.2.1 on 2025-05-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userrating_comment_userrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'User Rating', 'verbose_name_plural': 'User Ratings'},
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'resource')},
        ),
        migrations.CreateModel(
            name='UserSavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Resource',
                'verbose_name_plural': 'User Saved Resources',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
